[package]
name = "pow-blockchain"
version = "0.1.0"
authors = ["Frank <lifrank@grinnell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
hex = "0.4.2"
byteorder = "1.3.4"